import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { AlertTriangle, ArrowRight, CheckCircle2, Download, ExternalLink, FileCheck2, FileQuestion, FileText, Landmark, Mail, PhoneCall, Printer, Receipt, Scale, ShieldCheck, Stethoscope } from "lucide-react";
import { MedicalBillCaseDashboard } from "@/components/medical-bill-case-dashboard";
import { PageHero } from "@/components/shared/PageHero";
import { SectionHeading } from "@/components/shared/SectionHeading";
import { Button } from "@/components/ui/button";
import { trackSiteEvent } from "@/lib/analytics";
import { useSeo } from "@/lib/seo";

type RouteId = "eob" | "hospital" | "professional" | "denial" | "assistance" | "collections" | "mismatch" | "none";
type Route = { id: RouteId; title: string; short: string; icon: typeof FileText; is: string; not: string; checks: string[]; mistakes: string[]; questions: string[]; next: string; href: string; cta: string; official: string; officialLabel: string };

const routes: Route[] = [
  { id:"eob", title:"Explanation of Benefits", short:"Usually an insurer explanation, not a bill.", icon:FileCheck2, is:"A payer document showing claim status, allowed amount, plan payment, and possible patient responsibility.", not:"It is generally not the provider's request for payment.", checks:["Match the service date and provider.","Find claim status and patient responsibility.","Locate the matching provider bill before paying."], mistakes:["Paying from the EOB alone.","Treating a pending claim as final."], questions:["Has the provider sent a matching bill?","Do the amounts match?"], next:"Match the EOB and bill line by line.", href:"/tools/eob-to-bill-match-checker", cta:"Compare the EOB and bill", official:"https://www.cms.gov/medical-bill-rights/help/guides/explanation-of-benefits", officialLabel:"CMS EOB guide" },
  { id:"hospital", title:"Hospital or facility bill", short:"A payment request from the facility.", icon:Receipt, is:"A facility bill that may include room, supplies, equipment, and institutional services.", not:"It may not include physicians, anesthesia, labs, imaging, pathology, or ambulance charges.", checks:["Confirm the payer processed the claim.","Compare the balance with the payer explanation.","Request an itemized bill and assistance policy when needed."], mistakes:["Assuming one visit creates one bill.","Starting a long payment plan before checking assistance."], questions:["Which services are included?","Can the account be held during review?"], next:"Use the guided review before treating the first balance as final.", href:"/tools/medical-bill-review-flow", cta:"Start the bill review", official:"https://www.irs.gov/charities-non-profits/requirements-for-501c3-hospitals-under-the-affordable-care-act-section-501r", officialLabel:"IRS hospital requirements" },
  { id:"professional", title:"Physician or professional bill", short:"A separate clinician or group bill.", icon:Stethoscope, is:"A professional-services bill that can arrive separately from the facility bill.", not:"A separate bill is not automatically a duplicate.", checks:["Identify the billing group and date.","Find the matching payer claim.","Check network processing and patient responsibility."], mistakes:["Calling the facility about an independent bill.","Assuming an unfamiliar group proves fraud."], questions:["What service was provided?","Which payer claim matches it?"], next:"Identify the bill owner, then compare it with the payer explanation.", href:"/articles/why-one-hospital-visit-can-create-multiple-bills", cta:"Understand multiple bills", official:"https://www.cms.gov/medical-bill-rights", officialLabel:"CMS medical-bill rights" },
  { id:"denial", title:"Denial or authorization notice", short:"A written decision with a reason and deadline.", icon:AlertTriangle, is:"A notice explaining why a claim, service, medication, or authorization was not approved as submitted.", not:"It is not always the final available decision; follow the written notice.", checks:["Read the exact reason.","Locate the review or appeal deadline.","Identify missing evidence and who must submit it."], mistakes:["Calling before reading the notice.","Using a generic appeal without following instructions."], questions:["What exact step is missing?","What method and deadline apply?"], next:"Organize the notice, deadline, and provider-plan questions.", href:"/tools/prior-authorization-next-step-guide", cta:"Build the next-step plan", official:"https://www.healthcare.gov/appeal-insurance-company-decision/", officialLabel:"HealthCare.gov appeals" },
  { id:"assistance", title:"Financial-assistance paperwork", short:"A hospital-specific application or policy.", icon:FileText, is:"A process that may consider household, income, insurance, services, and hospital policy.", not:"It is not universal and may exclude separate professional groups.", checks:["Request the written policy and summary.","Confirm covered entities and services.","List documents, submission steps, and timing."], mistakes:["Assuming insurance makes you ineligible.","Submitting without keeping a copy."], questions:["Will collections pause during review?","Can it apply to prior accounts?"], next:"Gather the policy, application, document list, and account-hold instructions.", href:"/articles/check-hospital-financial-assistance-before-paying", cta:"Open the assistance guide", official:"https://www.irs.gov/charities-non-profits/requirements-for-501c3-hospitals-under-the-affordable-care-act-section-501r", officialLabel:"IRS Section 501(r)" },
  { id:"collections", title:"Collections letter or warning", short:"A time-sensitive unpaid-balance notice.", icon:PhoneCall, is:"A notice that a provider or collector says a balance remains unpaid.", not:"It does not remove the need to verify the original bill, claim, disputes, and assistance status.", checks:["Identify the original creditor and balance.","Gather bills, payer notices, disputes, and assistance records.","Read every deadline and verify current rights."], mistakes:["Ignoring a legitimate deadline.","Sharing unnecessary medical details."], questions:["What original balance is identified?","Is another review unresolved?"], next:"Verify the account and preserve written records before responding.", href:"/tools/medical-bill-review-flow", cta:"Organize the review", official:"https://www.consumerfinance.gov/consumer-tools/medical-debt/", officialLabel:"CFPB medical-debt resources" },
  { id:"mismatch", title:"Documents do not match", short:"The EOB, bill, or portal conflicts.", icon:Scale, is:"A reconciliation problem involving timing, billing entities, claim status, adjustments, network status, or authorization.", not:"A mismatch alone does not prove an error or determine what is owed.", checks:["Match dates and billing entities.","Confirm pending, processed, adjusted, or denied status.","Ask the owner of the inconsistent number for a written explanation."], mistakes:["Comparing unrelated lines.","Calling several organizations without assigning the next action."], questions:["Which exact line conflicts?","Is the difference temporary or final?"], next:"Use the comparison checker and save a case summary.", href:"/tools/eob-to-bill-match-checker", cta:"Compare the documents", official:"https://www.cms.gov/medical-bill-rights", officialLabel:"CMS medical-bill rights" },
  { id:"none", title:"No document yet", short:"Prepare before a bill or EOB arrives.", icon:FileQuestion, is:"A preparation stage for estimates, authorizations, expected billing groups, and contacts.", not:"A verbal estimate is not always the final processed responsibility.", checks:["Save written estimates and authorizations.","Ask which groups may bill separately.","Know where payer notices and bills will appear."], mistakes:["Relying only on a verbal estimate.","Assuming every clinician shares facility network status."], questions:["Who may bill separately?","What written cost information exists?"], next:"Prepare a folder and review the first payer explanation before paying.", href:"/articles/questions-to-ask-before-a-medical-appointment-cost", cta:"Prepare for medical costs", official:"https://www.cms.gov/medical-bill-rights/help/guides/good-faith-estimate", officialLabel:"CMS estimate guide" },
];

const beforePay = ["Identify the document.","Match date, provider, and service.","Confirm payer processing.","Compare charge, allowed amount, adjustments, plan payment, and patient responsibility.","Separate facility and professional bills.","Request an itemized bill when unclear.","Check network and current surprise-billing protections when relevant.","Check hospital financial assistance before long payment plans or high-interest debt.","Organize denial reasons and deadlines exactly as written.","Record every call, promise, and follow-up date."];
const sources = [["CMS Medical Bill Rights","https://www.cms.gov/medical-bill-rights"],["CMS Explanation of Benefits","https://www.cms.gov/medical-bill-rights/help/guides/explanation-of-benefits"],["HealthCare.gov Appeals","https://www.healthcare.gov/appeal-insurance-company-decision/"],["IRS Hospital Requirements","https://www.irs.gov/charities-non-profits/requirements-for-501c3-hospitals-under-the-affordable-care-act-section-501r"],["CFPB Medical Debt","https://www.consumerfinance.gov/consumer-tools/medical-debt/"],["Medicare Appeals","https://www.medicare.gov/claims-appeals/how-do-i-file-an-appeal"]] as const;

const MedicalBillReviewToolkitPage = () => {
  const [selected, setSelected] = useState<RouteId | null>(null);
  const route = routes.find((item) => item.id === selected);
  useSeo({ title:"Medical Bill Response System", description:"Identify an EOB, bill, denial, assistance form, or collection notice and follow a private RN-led review sequence before paying.", canonicalPath:"/insurance/medical-bill-review-toolkit" });
  useEffect(() => { trackSiteEvent("medical_bill_hub_view", { event_category:"medical_bill", entry_surface:"response_system" }); }, []);
  const choose = (id: RouteId) => { setSelected(id); ["document_router_start","document_router_result_type","document_router_complete"].forEach((event) => trackSiteEvent(event, { event_category:"medical_bill", route_type:id })); trackSiteEvent("tool_completion", { event_category:"medical_bill", tool_id:"document_router" }); requestAnimationFrame(() => document.getElementById("document-result")?.scrollIntoView({ behavior:"smooth" })); };
  const pack = () => trackSiteEvent("response_pack_download", { event_category:"medical_bill", asset_id:"medical_bill_response_pack" });
  const print = () => { trackSiteEvent("print_or_save_action", { event_category:"medical_bill", action_type:"page_print" }); window.print(); };

  return <>
    <PageHero eyebrow="RN-led healthcare money navigation" title="Medical Bill Response System" description="Identify the document, check the claim story, organize the next call, and verify the correct official source before treating a balance as final.">
      <Button asChild variant="hero" size="lg"><a href="#document-router">Identify my document <ArrowRight className="h-4 w-4" /></a></Button>
      <Button asChild variant="outline" size="lg"><a href="/downloads/medical-bill-response-pack.html" onClick={pack}><Download className="h-4 w-4" /> Open response pack</a></Button>
    </PageHero>
    <div className="container space-y-16 py-12 md:space-y-20 md:py-16">
      <section className="rounded-[2rem] border border-primary/20 bg-primary-soft/30 p-6 shadow-card"><ShieldCheck className="h-7 w-7 text-primary" /><h2 className="mt-4 font-display text-2xl font-bold">Start with the document, not the dollar amount.</h2><p className="mt-3 max-w-4xl text-sm leading-relaxed text-muted-foreground">An EOB is generally not a bill. Do not ignore a legitimate deadline, but do not assume every first balance is final. Identify the document, confirm processing, and keep a dated record.</p><div className="mt-5 rounded-2xl border border-border bg-card p-4 text-sm text-muted-foreground"><strong className="text-foreground">Privacy:</strong> Do not enter names, diagnoses, member IDs, claim numbers, account numbers, or other protected information. This system does not decide coverage, coding, liability, collectibility, or what you owe.</div></section>

      <section id="document-router" className="scroll-mt-24"><SectionHeading centered eyebrow="Step 1" title="What document are you holding?" description="Choose the closest match for the first checks, mistakes, questions, and safest next action." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{routes.map((item) => { const Icon=item.icon; return <button key={item.id} type="button" aria-pressed={selected===item.id} onClick={() => choose(item.id)} className={`min-h-40 rounded-3xl border p-5 text-left shadow-card focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${selected===item.id?"border-primary bg-primary-soft/40":"border-border bg-card hover:border-primary/35"}`}><Icon className="h-5 w-5 text-primary" /><h3 className="mt-4 font-display text-lg font-bold">{item.title}</h3><p className="mt-2 text-sm text-muted-foreground">{item.short}</p></button>; })}</div>
      {route && <article id="document-result" aria-live="polite" className="mt-8 scroll-mt-24 rounded-[2rem] border border-primary/25 bg-card p-6 shadow-hover"><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.14em] text-primary">Document classification</div><h2 className="mt-2 font-display text-3xl font-bold">{route.title}</h2><p className="mt-3 text-sm text-muted-foreground"><strong className="text-foreground">What it generally is:</strong> {route.is}</p><p className="mt-2 text-sm text-muted-foreground"><strong className="text-foreground">What it is not:</strong> {route.not}</p></div><Button type="button" variant="outline" onClick={print}><Printer className="h-4 w-4" /> Print or save result</Button></div><div className="mt-6 grid gap-4 lg:grid-cols-3">{[["First three checks",route.checks,CheckCircle2],["Common mistakes",route.mistakes,AlertTriangle],["Questions to ask",route.questions,FileText]].map(([title,items,Icon]) => <div key={String(title)} className="rounded-3xl border border-border p-5"><h3 className="font-display text-xl font-bold">{String(title)}</h3><ul className="mt-4 space-y-3 text-sm text-muted-foreground">{(items as string[]).map((item) => <li key={item} className="flex gap-2"><Icon className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{item}</li>)}</ul></div>)}</div><div className="mt-6 rounded-3xl bg-primary-soft/40 p-5"><div className="text-xs font-bold uppercase tracking-[.14em] text-primary">Safest next action</div><p className="mt-2 font-semibold">{route.next}</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Button asChild variant="hero"><Link to={route.href}>{route.cta} <ArrowRight className="h-4 w-4" /></Link></Button><Button asChild variant="outline"><a href={route.official} target="_blank" rel="noreferrer" onClick={() => trackSiteEvent("official_source_click", { event_category:"medical_bill", resource_id:route.id })}>{route.officialLabel} <ExternalLink className="h-4 w-4" /></a></Button></div></div></article>}</section>

      <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-[2rem] border border-border bg-card p-6 shadow-card"><h2 className="font-display text-3xl font-bold">Before you pay</h2><ol className="mt-5 space-y-3 text-sm text-muted-foreground">{beforePay.map((item,index)=><li key={item} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary-soft text-xs font-bold text-primary">{index+1}</span>{item}</li>)}</ol></div><div className="rounded-[2rem] border border-border bg-muted/25 p-6"><h2 className="font-display text-3xl font-bold">Common billing patterns</h2><div className="mt-5 space-y-4 text-sm text-muted-foreground"><p><strong className="text-foreground">One visit, several bills:</strong> facility, physician, lab, imaging, anesthesia, pathology, and ambulance organizations may bill separately.</p><p><strong className="text-foreground">EOB versus bill:</strong> the payer explains claim processing; the provider requests payment.</p><p><strong className="text-foreground">Billed versus allowed:</strong> the provider submits the billed charge; the plan recognizes an allowed amount under its rules.</p><p><strong className="text-foreground">Pending, denied, adjusted:</strong> pending is not final, a denial needs its written reason, and adjustments may change the balance.</p></div></div></section>

      <MedicalBillCaseDashboard />

      <section className="rounded-[2rem] border border-primary/20 bg-primary-soft/25 p-6 shadow-card"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><Download className="h-7 w-7 text-primary" /><h2 className="mt-4 font-display text-3xl font-bold">Medical Bill Response Pack</h2><p className="mt-3 max-w-3xl text-sm text-muted-foreground">Printable checklist, EOB-to-bill worksheet, call log, itemized-bill request script, assistance checklist, denial organizer, deadline tracker, and questions-before-paying sheet. Free, advertisement-free, and browser print/save-as-PDF ready.</p></div><div className="flex flex-col gap-3"><Button asChild variant="hero"><a href="/downloads/medical-bill-response-pack.html" onClick={pack}><Download className="h-4 w-4" /> Open printable pack</a></Button><Button asChild variant="outline"><Link to="/newsletter" onClick={() => { trackSiteEvent("medical_bill_email_signup", { event_category:"medical_bill", entry_surface:"response_system" }); trackSiteEvent("premium_pack_interest", { event_category:"medical_bill", offer_id:"response_pack_updates" }); }}><Mail className="h-4 w-4" /> Get toolkit updates</Link></Button></div></div></section>

      <section className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[2rem] border border-border bg-card p-6 shadow-card"><Stethoscope className="h-6 w-6 text-primary" /><h2 className="mt-3 font-display text-2xl font-bold">RN perspective</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Clinical care, discharge, insurance processing, and billing often move through different teams on different timelines. Identify each document, determine who owns the next action, and keep a dated record until the written claim and account status align.</p><p className="mt-3 text-xs text-muted-foreground">Andrew Ciccarelli, BSN, RN contributes bedside and discharge-process perspective. Official sources control factual billing and coverage guidance.</p></div><div><SectionHeading eyebrow="Official verification" title="Use the written notice and controlling source" description="A general guide cannot replace plan documents, hospital policies, state rules, or an official determination." /><div className="grid gap-3 sm:grid-cols-2">{sources.map(([title,href]) => <a key={href} href={href} target="_blank" rel="noreferrer" onClick={() => trackSiteEvent("official_source_click", { event_category:"medical_bill", resource_id:title })} className="rounded-2xl border border-border bg-card p-4 font-semibold shadow-card hover:border-primary/30"><Landmark className="mb-2 h-5 w-5 text-primary" />{title} <ExternalLink className="ml-1 inline h-4 w-4" /></a>)}</div></div></section>

      <section className="rounded-[2rem] border border-border bg-card p-6 text-sm text-muted-foreground shadow-card"><div className="grid gap-5 md:grid-cols-2"><div><strong className="text-foreground">Author and review</strong><p className="mt-2">Andrew Ciccarelli, BSN, RN. Published July 2026. Source-reviewed July 20, 2026 against linked CMS, HealthCare.gov, IRS, Medicare, and CFPB materials.</p></div><div><strong className="text-foreground">Review scope and limits</strong><p className="mt-2">Reviewed for patient-education clarity and consistency with official guidance. Not state-specific legal review. Does not decide coverage, coding, medical necessity, liability, collectibility, appeal success, or what is owed.</p></div></div><div className="mt-5 flex flex-wrap gap-4 border-t border-border pt-5 text-xs"><Link className="font-semibold text-primary" to="/methodology">Sources and methodology</Link><Link className="font-semibold text-primary" to="/editorial-policy">Editorial policy</Link><Link className="font-semibold text-primary" to="/disclosures">Disclosures</Link><Link className="font-semibold text-primary" to="/contact">Corrections and contact</Link></div></section>
    </div>
  </>;
};

export default MedicalBillReviewToolkitPage;
