import { useMemo, useState } from "react";
import { AlertTriangle, Copy, Scale } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { buildStudentLoanPriority, type StudentLoanPriorityInput } from "@/lib/studentLoanPriority";

const initial: StudentLoanPriorityInput = { loanType: "unknown", aprBand: "unknown", fullMatchCaptured: "unknown", emergencyFund: "unknown", forgivenessPath: "unknown", majorExpense: "unknown", monthlySurplus: "unknown" };
const humanize = (value: string) => value.replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export const StudentLoanPriorityBridge = () => {
  const [input, setInput] = useState(initial);
  const result = useMemo(() => buildStudentLoanPriority(input), [input]);
  const field = <K extends keyof StudentLoanPriorityInput>(key: K, label: string, options: StudentLoanPriorityInput[K][]) => <label className="space-y-2"><span className="text-sm font-bold">{label}</span><select className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" value={input[key]} onChange={(event) => setInput((current) => ({ ...current, [key]: event.target.value as StudentLoanPriorityInput[K] }))}>{options.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select></label>;
  const text = ["Student loans or retirement contributions?", `Do first: ${result.first}`, ...result.priorities.map((item) => `- ${item}`), "Verify:", ...result.verify.map((item) => `- ${item}`), result.warning].join("\n");
  return <section className="container pb-12 md:pb-16"><Card className="rounded-[2rem] border-primary/20 shadow-card"><CardHeader><Scale className="h-6 w-6 text-primary" /><CardTitle className="font-display text-2xl md:text-3xl">Student loans or more retirement contributions?</CardTitle><CardDescription>Use broad ranges to organize the next question. This does not calculate an individualized investment, tax, repayment, or forgiveness recommendation.</CardDescription></CardHeader><CardContent className="space-y-6"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{field("loanType", "Loan type", ["unknown", "federal", "private", "both"])}{field("aprBand", "Approximate APR band", ["unknown", "under-4", "4-7", "over-7"])}{field("fullMatchCaptured", "Full employer match captured?", ["unknown", "yes", "no"])}{field("emergencyFund", "Emergency-fund range", ["unknown", "under-1-month", "1-3-months", "3-plus-months"])}{field("forgivenessPath", "Forgiveness path under consideration?", ["unknown", "yes", "no"])}{field("majorExpense", "Major planned expense?", ["unknown", "yes", "no"])}{field("monthlySurplus", "Monthly surplus range", ["unknown", "under-250", "250-750", "over-750"])}</div><div className="rounded-2xl border border-primary/25 bg-primary-soft/25 p-5"><div className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Do this first</div><p className="mt-2 font-semibold leading-relaxed">{result.first}</p></div><div className="grid gap-4 lg:grid-cols-2"><div><h3 className="font-display text-xl font-bold">Priority logic</h3><ul className="mt-3 space-y-2 text-sm leading-relaxed text-muted-foreground">{result.priorities.map((item) => <li key={item}>• {item}</li>)}</ul></div><div><h3 className="font-display text-xl font-bold">Verify before acting</h3><ul className="mt-3 space-y-2 text-sm leading-relaxed text-muted-foreground">{result.verify.map((item) => <li key={item}>• {item}</li>)}</ul></div></div><div className="flex items-start gap-2 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-relaxed text-amber-950"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />{result.warning}</div><Button type="button" variant="outline" onClick={() => navigator.clipboard.writeText(text)}><Copy className="h-4 w-4" />Copy priority summary</Button></CardContent></Card></section>;
};
