// Generated by scripts/generate-runtime-seo-manifest.mjs. Do not edit by hand.

export type RuntimeArticleSeoMeta = {
  slug: string;
  title: string;
  description: string;
  category: string;
  publishedAt?: string;
  lastReviewedAt?: string;
};

export type RuntimeTopicSeoMeta = {
  slug: string;
  title: string;
  description: string;
};

export type RuntimeToolSeoMeta = {
  slug: string;
  title: string;
  description: string;
};

export const RUNTIME_ARTICLE_SEO_META = [
  {
    "slug": "what-employer-benefit-changes-should-i-compare",
    "title": "What Employer-Benefit Changes Should I Compare During Open Enrollment?",
    "description": "Compare the changes that can alter cost, access, employer value, or protection before you repeat last year's elections.",
    "category": "Workplace Benefits",
    "publishedAt": "2026-07-12",
    "lastReviewedAt": "2026-07-12"
  },
  {
    "slug": "does-medicare-cover-long-term-care",
    "title": "Does Medicare Cover Long-Term Care?",
    "description": "A plain-English answer to the Medicare long-term care gap, including the difference between skilled care and custodial care.",
    "category": "Medicare"
  },
  {
    "slug": "does-medicare-cover-rehab-after-hospital-stay",
    "title": "Does Medicare Cover Rehab After a Hospital Stay?",
    "description": "Understand when Medicare may cover short-term rehab, what can block coverage, and what families should ask before discharge.",
    "category": "Medicare"
  },
  {
    "slug": "medicare-vs-medicaid-what-is-the-difference",
    "title": "Medicare vs Medicaid: What Is the Difference?",
    "description": "Separate Medicare and Medicaid in plain English so patients and families know which program solves which problem.",
    "category": "Medicare"
  },
  {
    "slug": "what-does-medicare-not-cover",
    "title": "What Does Medicare Not Cover?",
    "description": "A plain-English list of common Medicare coverage gaps that create surprise costs for patients and families.",
    "category": "Medicare"
  },
  {
    "slug": "why-do-i-still-owe-money-with-medicare",
    "title": "Why Do I Still Owe Money With Medicare?",
    "description": "Explain why Medicare can pay part of a claim while the patient still owes premiums, deductibles, copays, coinsurance, or uncovered costs.",
    "category": "Medicare"
  },
  {
    "slug": "how-much-should-a-nurse-put-in-403b-per-paycheck",
    "title": "How Much Should a Nurse Put in a 403(b) Per Paycheck?",
    "description": "A practical paycheck framework for nurses and healthcare workers deciding what 403(b) contribution percentage to start with.",
    "category": "Build Wealth"
  },
  {
    "slug": "how-hospital-403b-matching-works",
    "title": "How Does a Hospital 403(b) Match Work? Examples and Vesting",
    "description": "See how hospital 403(b) matching works, including common formulas, contribution examples, vesting, eligible pay, and 401(a) employer deposits.",
    "category": "Build Wealth",
    "lastReviewedAt": "2026-07-13"
  },
  {
    "slug": "how-to-pick-retirement-investments-at-work",
    "title": "How to Pick Retirement Investments at Work",
    "description": "A plain-English guide to target-date funds, S&P 500 index funds, expense ratios, risk, and changing investments inside a workplace retirement account.",
    "category": "Build Wealth"
  },
  {
    "slug": "healthcare-worker-money-map",
    "title": "The Healthcare Worker Money Map",
    "description": "A plain-English order of operations for turning a healthcare paycheck into savings, retirement contributions, and long-term wealth.",
    "category": "Build Wealth"
  },
  {
    "slug": "how-healthcare-workers-can-invest-without-picking-stocks",
    "title": "How Healthcare Workers Can Invest Without Picking Stocks",
    "description": "A simple investing guide for healthcare workers who want long-term growth without turning investing into a second job.",
    "category": "Build Wealth"
  },
  {
    "slug": "savings-rate-that-actually-changes-your-life",
    "title": "The Savings Rate That Actually Changes Your Life",
    "description": "Why savings rate matters more than tiny budgeting hacks, especially for healthcare workers trying to buy back time.",
    "category": "Build Wealth"
  },
  {
    "slug": "roth-vs-traditional-403b-healthcare-workers",
    "title": "Roth vs Traditional 403(b) for Healthcare Workers",
    "description": "A practical way to think about current tax savings, future tax flexibility, and paycheck stress when choosing 403(b) contributions.",
    "category": "Build Wealth"
  },
  {
    "slug": "can-healthcare-workers-reach-financial-independence",
    "title": "Can Healthcare Workers Reach Financial Independence?",
    "description": "A realistic FI guide for workers who want more freedom without pretending every shift is easy or every budget is painless.",
    "category": "Build Wealth"
  },
  {
    "slug": "cash-vs-investing-when-you-feel-behind",
    "title": "Should You Keep Cash or Invest It? A Practical Decision Framework",
    "description": "Use a practical cash-versus-investing framework based on emergency reserves, near-term expenses, debt, employer matching, and time horizon.",
    "category": "Build Wealth",
    "lastReviewedAt": "2026-07-15"
  },
  {
    "slug": "can-you-live-off-dividends-passive-income-guide",
    "title": "Can You Live Off Dividends? A Plain-English Passive Income Guide",
    "description": "A grounded explanation of dividend income, total return, and why passive income still needs a large asset base.",
    "category": "Build Wealth"
  },
  {
    "slug": "money-stress-after-hard-shift",
    "title": "Money Stress After a Hard Shift",
    "description": "How to stop stress from turning into spending, avoidance, or panic decisions after exhausting healthcare work.",
    "category": "Build Wealth"
  },
  {
    "slug": "earn-more-without-burning-out-bedside",
    "title": "How to Earn More Without Burning Out at Bedside",
    "description": "A career-income guide for healthcare workers who want more money and more options without relying only on extra shifts.",
    "category": "Build Wealth"
  },
  {
    "slug": "managing-money-has-never-been-easier-or-harder",
    "title": "Managing Money Has Never Been Easier—or Harder",
    "description": "Why financial apps make money easier to manage but harder to stop thinking about—and how selective friction can improve spending and investing decisions.",
    "category": "Build Wealth"
  },
  {
    "slug": "use-credit-cards-without-credit-card-debt",
    "title": "How to Use a Credit Card Without Carrying Credit Card Debt",
    "description": "Learn how to use a credit card, build credit, set up full-balance autopay, use secured-card guardrails, and avoid expensive credit-card debt.",
    "category": "Build Wealth"
  },
  {
    "slug": "open-enrollment-mistakes-healthcare-workers",
    "title": "Open Enrollment Mistakes Healthcare Workers Make Every Year",
    "description": "Avoid the benefit choices that quietly raise risk, reduce take-home pay, or leave healthcare workers underprotected.",
    "category": "Open Enrollment"
  },
  {
    "slug": "premium-deductible-out-of-pocket-open-enrollment",
    "title": "Premium, Deductible, and Out-of-Pocket Max: How to Compare Health Plans",
    "description": "Learn the three numbers that decide whether a health plan is cheap, risky, or actually a good fit.",
    "category": "Open Enrollment"
  },
  {
    "slug": "spouse-family-health-insurance-open-enrollment",
    "title": "Can You Add a Spouse to Your Health Insurance? Rules, Costs, and Dual Coverage",
    "description": "Learn when you can add a spouse to health insurance, how qualifying life events work, and how to compare surcharges, dual coverage, and family costs.",
    "category": "Open Enrollment",
    "lastReviewedAt": "2026-07-13"
  },
  {
    "slug": "prescription-coverage-open-enrollment-checklist",
    "title": "How to Check Prescription Drug Coverage Before Choosing a Health Plan",
    "description": "Check prescription drug coverage before choosing a health plan, including formularies, tiers, pharmacies, deductibles, and prior authorization.",
    "category": "Open Enrollment",
    "lastReviewedAt": "2026-07-13"
  },
  {
    "slug": "network-checklist-open-enrollment",
    "title": "In-Network Is Not One Checkbox: What to Verify During Open Enrollment",
    "description": "Use a practical network checklist before choosing a plan for the next year.",
    "category": "Open Enrollment"
  },
  {
    "slug": "disability-insurance-healthcare-workers-open-enrollment",
    "title": "Disability Insurance for Healthcare Workers: The Benefit You Should Not Ignore",
    "description": "Understand short-term and long-term disability before an injury or illness threatens your income.",
    "category": "Open Enrollment"
  },
  {
    "slug": "employer-life-insurance-open-enrollment",
    "title": "Employer Life Insurance: Helpful, But Usually Not a Full Plan",
    "description": "Know what basic life, supplemental life, guaranteed issue, and portability mean before checking the box.",
    "category": "Open Enrollment"
  },
  {
    "slug": "accident-critical-illness-hospital-indemnity-open-enrollment",
    "title": "Accident vs. Critical Illness vs. Hospital Indemnity Insurance",
    "description": "Compare accident, critical illness, and hospital indemnity insurance by benefit trigger, payout, exclusions, and fit with your health plan.",
    "category": "Open Enrollment",
    "lastReviewedAt": "2026-07-13"
  },
  {
    "slug": "dental-vision-insurance-open-enrollment",
    "title": "Dental and Vision Insurance: What to Check Before Adding Them",
    "description": "Avoid overbuying add-ons by checking annual maximums, frequency limits, and real expected use.",
    "category": "Open Enrollment"
  },
  {
    "slug": "health-fsa-vs-dependent-care-fsa",
    "title": "Health FSA vs Dependent Care FSA: Same Name, Totally Different Use",
    "description": "Do not mix up medical expense money with childcare or dependent-care money.",
    "category": "Open Enrollment"
  },
  {
    "slug": "open-enrollment-paycheck-impact",
    "title": "How Open Enrollment Changes Your Paycheck",
    "description": "See how benefit elections stack up before your first paycheck of the new plan year surprises you.",
    "category": "Open Enrollment"
  },
  {
    "slug": "beneficiaries-open-enrollment-checklist",
    "title": "The 10-Minute Open Enrollment Task That Prevents a Legal Mess",
    "description": "Use open enrollment to update beneficiaries before life changes create avoidable problems.",
    "category": "Open Enrollment"
  },
  {
    "slug": "from-the-bedside-medicare-prescription-cost",
    "title": "Why Is My Prescription So Expensive If I Have Medicare?",
    "description": "A bedside Medicare drug-cost story showing why a covered prescription can still create a painful pharmacy bill — and what to ask before giving up on it.",
    "category": "Medicare"
  },
  {
    "slug": "from-the-bedside-long-term-care-medicaid-hospital-delay",
    "title": "From the Bedside: Long-Term Care Medicaid Should Not Wait Until a Crisis",
    "description": "A bedside look at why older adults can get stuck in the hospital while families scramble for long-term care Medicaid and nursing home placement.",
    "category": "Medicaid"
  },
  {
    "slug": "how-healthcare-workers-should-compare-job-offers",
    "title": "How Healthcare Workers Should Compare Two Job Offers",
    "description": "Compare salary, overtime, differentials, benefits, PTO, insurance premiums, commute burden, and schedule tradeoffs before accepting a healthcare job.",
    "category": "Healthcare Worker Pay"
  },
  {
    "slug": "why-one-hospital-visit-can-create-multiple-bills",
    "title": "Why One Hospital Visit Can Create Multiple Bills",
    "description": "Understand why a single ER visit, surgery, or hospital stay can produce separate bills from different groups.",
    "category": "Hospital Bills"
  },
  {
    "slug": "facility-fee-vs-professional-fee",
    "title": "Facility Fee vs. Professional Fee: Why One Visit Can Produce Two Bills",
    "description": "Learn the difference between a facility fee and professional fee, why one visit can create two bills, and what to verify before paying.",
    "category": "Hospital Bills",
    "lastReviewedAt": "2026-07-13"
  },
  {
    "slug": "observation-vs-inpatient-status",
    "title": "Observation vs Inpatient Status: The Hospital Word That Can Change the Bill",
    "description": "Understand why staying overnight does not always mean a patient was formally admitted as an inpatient.",
    "category": "Medicare"
  },
  {
    "slug": "in-network-hospital-out-of-network-bills",
    "title": "In-Network Hospital Does Not Always Mean Every Bill Is In-Network",
    "description": "Understand why separate clinicians or services can create network surprises even when the hospital itself is covered.",
    "category": "Insurance"
  },
  {
    "slug": "allowed-amount-medical-bills",
    "title": "Allowed Amount: The Number That Actually Matters on a Medical Bill",
    "description": "Learn why the billed charge is not always the number your insurance uses to calculate your share.",
    "category": "Insurance"
  },
  {
    "slug": "prior-authorization-explained",
    "title": "What Is Prior Authorization? Why Insurance Can Delay Doctor-Recommended Care",
    "description": "Learn what prior authorization is, why insurance may delay doctor-recommended care, and what to do when a request is pending or denied.",
    "category": "Insurance",
    "lastReviewedAt": "2026-07-13"
  },
  {
    "slug": "check-hospital-financial-assistance-before-paying",
    "title": "Before You Pay a Hospital Bill, Check Financial Assistance",
    "description": "Know when to ask for charity care or financial assistance before draining savings or using a credit card.",
    "category": "Hospital Bills"
  },
  {
    "slug": "insurance-is-future-planning",
    "title": "Insurance Is Future Planning, Not Just a Monthly Bill",
    "description": "See why health insurance, Medicare, Medicaid, and long-term care planning matter most before a hospitalization, diagnosis, rehab stay, or daily-care need turns coverage into a family financial decision.",
    "category": "Insurance"
  },
  {
    "slug": "medicare-advantage-vs-original-medicare-2026",
    "title": "Medicare Advantage vs. Original Medicare in 2026: Key Tradeoffs",
    "description": "Compare Medicare Advantage and Original Medicare in 2026 by provider access, premiums, cost sharing, drug coverage, prior authorization, travel, and Medigap.",
    "category": "Medicare",
    "lastReviewedAt": "2026-07-15"
  },
  {
    "slug": "hsa-vs-fsa-healthcare-workers",
    "title": "HSA vs FSA: The Plain-English Guide for Healthcare Workers",
    "description": "Know when an HSA, FSA, or both can help lower taxes without creating open-enrollment regret.",
    "category": "Workplace Benefits"
  },
  {
    "slug": "medicare-medicaid-changes-january-2027",
    "title": "Medicare and Medicaid Changes Scheduled for January 1, 2027",
    "description": "A plain-English guide to the scheduled 2027 Medicaid eligibility rollout and the practical areas Medicare patients, caregivers, and hospitals should watch.",
    "category": "Medicare & Medicaid"
  },
  {
    "slug": "obbb-overtime-tax-deduction-healthcare-workers",
    "title": "The OBBB Overtime Tax Deduction, Explained for Healthcare Workers",
    "description": "Understand why the new overtime rule matters, what part of overtime may qualify, and why it is not the same as making every overtime dollar tax-free.",
    "category": "Workplace Benefits"
  },
  {
    "slug": "backup-care-plans-for-busy-healthcare-workers",
    "title": "Backup Childcare for Healthcare Workers: A Shift-Proof Plan",
    "description": "Create a backup childcare plan for nursing shifts, weekends, call, illness, and school closures, including employer benefits and cost planning.",
    "category": "Spending",
    "lastReviewedAt": "2026-07-13"
  },
  {
    "slug": "workplace-benefits-definitions",
    "title": "Workplace Benefits Definitions",
    "description": "Decode open enrollment paperwork without calling HR.",
    "category": "Workplace Benefits"
  },
  {
    "slug": "deductible-copay-coinsurance-out-of-pocket-max",
    "title": "Deductible vs. Copay vs. Coinsurance vs. Out-of-Pocket Maximum",
    "description": "Learn the difference between a deductible, copay, coinsurance, and out-of-pocket maximum with a simple medical-bill example.",
    "category": "Insurance",
    "lastReviewedAt": "2026-07-13"
  },
  {
    "slug": "how-to-read-an-eob",
    "title": "How to Read an Explanation of Benefits (EOB) Before Paying a Medical Bill",
    "description": "Learn how to read an Explanation of Benefits, match it to a medical bill, and verify allowed amount, insurance payment, and patient responsibility.",
    "category": "Hospital Bills",
    "lastReviewedAt": "2026-07-13"
  },
  {
    "slug": "why-er-visit-is-expensive",
    "title": "Why an ER Visit Can Be So Expensive",
    "description": "Understand the pieces that can turn one emergency visit into several separate charges.",
    "category": "Hospital Bills"
  },
  {
    "slug": "medicare-options-explained",
    "title": "Medicare Options Explained",
    "description": "Understand Original Medicare, Medicare Advantage, Part D, Medigap, and Medicaid without getting buried in insurance language.",
    "category": "Medicare",
    "publishedAt": "2026-06-01",
    "lastReviewedAt": "2026-07-12"
  },
  {
    "slug": "discharge-coverage-guide",
    "title": "Discharge Coverage Guide",
    "description": "Understand which post-hospital costs Medicare may cover after discharge — and which questions families should ask early.",
    "category": "Medicare"
  },
  {
    "slug": "short-term-rehab-after-hospital",
    "title": "Short-Term Rehab After the Hospital",
    "description": "Learn what Medicare and Medicaid may cover when a patient needs rehab after hospitalization.",
    "category": "Medicare"
  },
  {
    "slug": "home-health-after-discharge",
    "title": "Home Health After Discharge",
    "description": "Understand what Medicare home health can help with after discharge — and what it usually does not replace.",
    "category": "Medicare"
  },
  {
    "slug": "durable-medical-equipment-after-discharge",
    "title": "Durable Medical Equipment After Discharge",
    "description": "Learn how walkers, wheelchairs, oxygen, hospital beds, and other equipment may be covered after discharge.",
    "category": "Medicare"
  },
  {
    "slug": "long-term-care-and-custodial-care",
    "title": "Skilled Care vs. Custodial Care: What Medicare Usually Covers",
    "description": "Learn the difference between skilled care and custodial care, what Medicare may cover, and when Medicaid or separate long-term-care planning may matter.",
    "category": "Medicare",
    "lastReviewedAt": "2026-07-15"
  },
  {
    "slug": "medicaid-dual-eligibility-ltss",
    "title": "Medicaid, Dual Eligibility, and LTSS",
    "description": "Understand where Medicaid fits when Medicare does not cover the long-term care a family hoped for.",
    "category": "Medicaid"
  },
  {
    "slug": "plain-english-glossary",
    "title": "Plain-English Healthcare Finance Glossary",
    "description": "Insurance and Medicare terms defined like a human, not like a benefits packet.",
    "category": "Insurance"
  },
  {
    "slug": "hospital-cafe-habit",
    "title": "How Much Does Hospital Cafeteria Spending Cost Per Year?",
    "description": "Calculate the yearly cost of hospital cafeteria meals and coffee, then build a realistic shift-work spending plan instead of an all-or-nothing budget.",
    "category": "Spending",
    "lastReviewedAt": "2026-07-15"
  },
  {
    "slug": "healthcare-worker-discounts",
    "title": "Healthcare Worker Discounts and Perks Directory",
    "description": "Use healthcare discounts without letting them become an excuse to buy things you did not need.",
    "category": "Workplace Benefits"
  },
  {
    "slug": "burnout-overspending-overeating",
    "title": "Burnout, Overspending, and Overeating After Hard Shifts",
    "description": "Understand why hard shifts can trigger expensive or unhealthy coping patterns — without shame.",
    "category": "Spending"
  }
] satisfies RuntimeArticleSeoMeta[];

export const RUNTIME_TOPIC_SEO_META = [
  {
    "slug": "medicare-medicaid",
    "title": "Medicare & Medicaid",
    "description": "A quick guide to what each program does, how Medicare's parts fit together, and where long-term care gaps can appear."
  },
  {
    "slug": "workplace-benefits",
    "title": "Healthcare Worker Benefits Hub",
    "description": "Move from match and paycheck decisions to health-plan math, HSA or FSA choices, disability coverage, life insurance, and beneficiaries in one connected path."
  },
  {
    "slug": "retirement-accounts",
    "title": "Retirement Accounts",
    "description": "403(b), 401(a), 457(b), Roth vs Traditional — the workplace retirement vocabulary in plain English."
  },
  {
    "slug": "health-insurance",
    "title": "Health Insurance",
    "description": "Premium, deductible, copay, coinsurance, out-of-pocket max — translated into normal English."
  },
  {
    "slug": "patient-medical-costs",
    "title": "Patient Medical Costs",
    "description": "Hospital bills, EOBs, surprise charges — what's normal, what isn't, and what to ask."
  },
  {
    "slug": "hospital-economics",
    "title": "Hospital Economics",
    "description": "Why hospitals make decisions that feel confusing from the bedside or the bill."
  },
  {
    "slug": "behavior-burnout",
    "title": "Behavior & Burnout",
    "description": "Money habits that happen after hard shifts — without shame or fake discipline advice."
  },
  {
    "slug": "discounts-perks",
    "title": "Healthcare Worker Discounts & Perks",
    "description": "Use discounts as a tool, not as a shopping trigger."
  }
] satisfies RuntimeTopicSeoMeta[];

export const RUNTIME_TOOL_SEO_META = [
  {
    "slug": "obbb-overtime-deduction-estimator",
    "title": "OBBB Overtime Deduction Estimator",
    "description": "Estimate qualifying overtime premium, the deduction cap, and rough federal income-tax savings."
  },
  {
    "slug": "open-enrollment-final-checklist",
    "title": "Open Enrollment Final Checklist",
    "description": "Run a final, printable review of health, tax account, disability, life, and supplemental elections."
  },
  {
    "slug": "open-enrollment-paycheck-impact-calculator",
    "title": "Open Enrollment Paycheck Impact Calculator",
    "description": "Estimate how pre-tax and after-tax benefit elections may change take-home pay."
  },
  {
    "slug": "supplemental-benefits-decision-helper",
    "title": "Supplemental Benefits Decision Helper",
    "description": "Compare premiums and likely payout for accident, critical illness, and hospital indemnity coverage."
  },
  {
    "slug": "hsa-vs-fsa-decision-helper",
    "title": "HSA vs FSA Decision Helper",
    "description": "Compare tax savings, employer money, deductible risk, forfeiture risk, and provider needs."
  },
  {
    "slug": "hospital-bill-review-checklist",
    "title": "Hospital Bill Review Checklist",
    "description": "Organize the first review of a large, confusing, or surprising healthcare balance."
  },
  {
    "slug": "financial-assistance-checklist",
    "title": "Financial Assistance Checklist",
    "description": "Prepare the documents and questions for hospital charity care or financial assistance."
  },
  {
    "slug": "health-insurance-visit-cost-calculator",
    "title": "Health Insurance Visit Cost Calculator",
    "description": "Estimate yearly cost across premiums, deductible, copays, coinsurance, visits, and remaining maximum room."
  },
  {
    "slug": "student-loan-path-finder",
    "title": "Student Loan Path Finder",
    "description": "Separate federal forgiveness paths from private-loan payoff decisions before choosing a strategy."
  },
  {
    "slug": "private-student-loan-payoff-calculator",
    "title": "Private Student Loan Payoff Calculator",
    "description": "Compare minimum payments, extra payments, lump sums, and a possible refinance APR."
  },
  {
    "slug": "pslf-progress-estimator",
    "title": "PSLF Progress Estimator",
    "description": "Estimate payments remaining to 120 and identify the records that still need official verification."
  },
  {
    "slug": "student-loan-payment-calculator",
    "title": "Student Loan Payment Calculator",
    "description": "Estimate monthly payment, total paid, and interest over time for a balance, APR, and term."
  },
  {
    "slug": "medicare-cost-exposure-tool",
    "title": "Medicare Cost Exposure Tool",
    "description": "Create a rough planning snapshot for premiums, deductibles, prescriptions, and coinsurance."
  },
  {
    "slug": "hospital-cafe-savings-calculator",
    "title": "Hospital Cafe Savings Rate Calculator",
    "description": "See what recurring shift spending adds up to and what redirecting part of it could become."
  },
  {
    "slug": "medical-appointment-cost-preparation",
    "title": "Medical Appointment Cost Preparation Tool",
    "description": "Prepare network, authorization, estimate, facility-fee, separate-bill, payment, and financial-assistance questions before planned care."
  },
  {
    "slug": "state-medicaid-long-term-care-router",
    "title": "State Medicaid and Long-Term Care Program Router",
    "description": "Find the official state starting point for Medicaid coverage, Medicare cost help, nursing-facility care, or home- and community-based services."
  },
  {
    "slug": "childcare-benefits-decision-guide",
    "title": "Dependent Care FSA and Childcare Benefits Decision Guide",
    "description": "Coordinate a 2026 Dependent Care FSA, employer childcare help, predictable expenses, and federal tax-credit questions."
  },
  {
    "slug": "roth-vs-traditional-decision-helper",
    "title": "Roth vs Traditional Retirement Contribution Decision Helper",
    "description": "Compare current deduction value, possible future tax rates, pension income, cash flow, account mix, and retirement-access planning."
  },
  {
    "slug": "observation-vs-inpatient-status-guide",
    "title": "Observation vs Inpatient Hospital Status Guide",
    "description": "Prepare the written-status, notice, coverage, skilled-care, discharge, and deadline questions to ask the hospital and payer."
  },
  {
    "slug": "medicare-plan-verification-checklist",
    "title": "Medicare Plan Verification Checklist",
    "description": "Verify providers, prescriptions, prior authorization, costs, travel, supplemental benefits, annual changes, and enrollment timing."
  },
  {
    "slug": "debt-vs-retirement-router",
    "title": "Debt vs Retirement Contribution Decision Router",
    "description": "Order emergency savings, employer match, high-cost debt, federal loan protections, and sustainable retirement progress."
  }
] satisfies RuntimeToolSeoMeta[];
